### ISSUE TITLE
gulp serve fails

### ISSUE THREAD

**Issue by ngbravo** [ngbravo/gitscore#24]
When running `$ gulp serve`

I get:
```
}[17:42:03] Requiring external module babel-register
[17:42:04] Using gulpfile ~/workspace/gitscore/gulpfile.babel.js
[17:42:04] Starting 'serve'...
[17:42:04] Starting 'lint'...
[17:42:04] Finished 'lint' after 590 ms
[17:42:04] Starting 'clean'...
[17:42:04] Finished 'clean' after 21 ms
[17:42:04] Starting 'copy-manifest:dev'...
[17:42:04] Finished 'copy-manifest:dev' after 11 ms
[17:42:04] Starting 'images:dev'...
[17:42:05] Starting 'extras:dev'...
[17:42:05] Finished 'extras:dev' after 18 ms
[17:42:05] Finished 'images:dev' after 118 ms
[17:42:05] Starting 'webpack-dev-server'...
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1034:11)
    at exports._exceptionWithHostPort (util.js:1057:20)
    at Server._listen2 (net.js:1270:14)
    at listen (net.js:1306:10)
    at doListening (net.js:1421:7)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:10)
```

**Comment by ngbravo** [comment]
Just another process using 8080. Maybe we should switch to another port.
